### ISSUE TITLE
Project Code Review Feedback

### ISSUE THREAD

**Issue by benardop** [AbigiyaTY/Empowering-African-Women#2]
-  @AbigiyaTY , Good work done so far in this project 👍 . Just one observation I would wish to make: You may please try to change the color of the active tab on you page using css 'active' property.

**Comment by yasinabdmahmood** [comment]
Great job implementing the conference website, although I have a couple of notes on how to make it even better
- I suggest that you make the link for the different pages turn red when you user moves to the corresponding page 
so that the user is aware of which page they are currently on 
- Also I suggest you center the container for the program cards in the program section on the home page.
